### ISSUE TITLE
Error package name

### ISSUE THREAD

**Issue by mokaikai** [knockdata/spark-highcharts#10]
The correct package name is `com.knockdata.spark.highcharts`, not `com.knockdata.zeppelin.highcharts`.

**Comment by rockiey** [comment]
Thanks very much for pointing out the error. 

I have fixed the package name issue. Please help to verify if that's all. And feel free to report other issues or create pull requests.

That was due to repo rename from `zeppelin-highcharts` -> `spark-highcharts`. Since it was originally design only works inside zeppelin. The name changed to `spark-highcharts` after support in `spark-shell` and other `scala` project was added.

**Comment by mokaikai** [comment]
Thanks!
