### ISSUE TITLE
Paragraph Link in Zeppelin does not show up

### ISSUE THREAD

**Issue by HarvinderBhullar** [knockdata/spark-highcharts#20]
The paragraph link in Zeppelin does not show up the chart. In the firebug it shows highchart not defined.

**Comment by rockie-yang** [comment]
I guess you are using your existing Zeppelin. Which you need load highcharts your self. 

ref https://github.com/knockdata/spark-highcharts/blob/master/docs/UseInZeppelin.md

**Comment by HarvinderBhullar** [comment]
Hi Rockie .. The chart show up in the Zeppelin Paragraph.. but when I am creating a paragraph link. The chart does not show up in the link

**Comment by rockie-yang** [comment]
It does work on my mbp. 

Are you load Highcharts.js according to  https://github.com/knockdata/spark-highcharts/blob/master/docs/UseInZeppelin.md? I have not tried linked for this solution. This might not working, because the linked page does not have highcharts loaded. 

Or Using docker image knockdata/zeppelin-highcharts? 

Or build zeppelin to include Highcharts.js

**Comment by HarvinderBhullar** [comment]
Thanks for the clarification.. Since, I am on AWS EMR the mentioned solution is not available.
